development:
  adapter: postgresql
  database: visite_uma_escola_development
  host: localhost
  user: postgres
  password: root
  pool: 5
  timeout: 5000
  template: template0

test: &test
  adapter: postgresql
  database: visite_uma_escola_test
  host: localhost
  user: postgres
  password: root
  pool: 5
  timeout: 5000
  template: template0

production:
  adapter: postgresql
  database: visite_uma_escola_production
  host: localhost
  user: postgres
  password: root
  pool: 5
  timeout: 5000
  template: template0